title: Semicertain
theme: jekyll-theme-primer

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  
collections:
  posts:
    title: Posts
    output: true
exclude:
- README.md
permalink: "/:categories/:title/"
